### ISSUE TITLE
add_data does not detect file type and tries to always load lammps

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#213]
**Describe the bug**

`test_project.add_data('./trajectory.extxyz')``
uses the Lammps file loader, even though it is clearly an `.extxyz` file

**Expected behavior**
We should try to distinguish the file type by the ending.

**Comment by PythonFZ** [comment]
This also affects https://github.com/zincware/MDSuite/blob/8efed9524868b46a75f2c494d9ffbb37614d72ab/mdsuite/project.py#L218 because it is currently not possible to load `extxyz` data

**Comment by SamTov** [comment]
It is a little more complicated in terms of a .xyz extension but certainly for .extxzy we can enforce this. There is no lammps trajectory extension and often people will write .xyz anyway.

In the case of the project class that is certainly problematic. I would propose a file identification module in the meta_functions module or perhaps better as a standalone in the file_io package.
