### ISSUE TITLE
Add sql logging to debug mode

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#217]
**What feature would you like to see added?**
On line 44 of the properties database module we have 
```
self.engine = sa.create_engine(f"sqlite+pysqlite:///{self.name}", echo=False, future=True)
```
where the logging of sql operations is suppressed. We should allow for echo to be set to true in the case of a logging debug call as it would be valuable database information.

**Describe how this feature would improve the code**
We would have a lot more information about data management during operations in the case of a debug.

**Describe how this feature would work/possible implementations**
I think a general debug argument could be added either to the Experiment or Project class or both. Upon being given debug=True all relevant operation enter debug mode and we can sort through the data from there.

**Comment by PythonFZ** [comment]
Apparently one can use the `logging` with SQLAlchemy as described here https://docs.sqlalchemy.org/en/14/core/engines.html#configuring-logging

For changing the logging level during runtime I tested the following, assuming that

```py
stream_handler = logging.StreamHandler(sys.stdout)
stream_handler.setLevel(logging.INFO)  # <- stdout loglevel
```

```py
>> log = logging.getLogger(__file__)
>> log.debug('DEBUG')
(nothing)
>> level = logging.DEBUG
>> logger = logging.getLogger()
>> logger.setLevel(level)
>> for handler in logger.handlers:
>>     handler.setLevel(level)

>> log.debug('<DEBUG>')
2021-05-06 16:46:05,341 (DEBUG) - <DEBUG>
```

Do you want to add it as `args/kwargs` to the project class? At this point, if you would change it anywhere in the code, it'll be applied for every log - also outside the experiment/project. If we want to make it e.g. experiment specific, I think we may need a `sys.stdout` logger per experiment.

**Comment by SamTov** [comment]
Has this been implemented or resolved?
