### ISSUE TITLE
Returned series data is not what is fit during operations

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#219]
**Describe the bug**
The data we return when a calculator is called is rarely directly what is used for the calculation internally. This means that users cannot directly just fit the data and must apply some operations on it to make it usable. 

**To Reproduce**
Run an Einstein diffusion plot, plot the resulting data yourself and try to get the coefficient by a fit. 

**Expected behaviour**
When someone fits the resulting data it should give the correct number for the Einstein plots. In the case of GK we return normalised plots which is flexible enough.

**Comment by PythonFZ** [comment]
Might be fixed in 8c18b99
