### ISSUE TITLE
Improve file reading options.

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#221]
**What feature would you like to see added?**
We should have the ability to read more file formats.

**Describe how this feature would improve the code**
It would allow for a more general code base.

**Describe how this feature would work/possible implementations**
We have several options:

* Use the [MDAnalysis](https://github.com/MDAnalysis/mdanalysis) file reading engine.
* Use the [ASE](https://github.com/qsnake/ase) file reading engine.
* Write our own.

The first two options will bring a lot of overhead which we may not want to deal with. But it is the fastest way to get it running.

**Comment by PythonFZ** [comment]
I don't think that the overhead is necessarily a bad think. We could decide on a default file reader and also reference the specific documentation. Additionally we would have an expert feature to load more files with different readers. In that case someone would only go for the non default reader if they have a special file format and they won't even notice the overhead.

- [openbabel](https://github.com/openbabel/openbabel) could be one more tool.

**Comment by SamTov** [comment]
Originally I left openbabel out as I was worried about speed with large trajectories but I see that they also have fingerprint and molecule specific options which could also be a great help with some of our molecule analysis. I think the only factor we should consider is speed. We have the infrastructure to also do the other features so speed seems to be like the deciding factor.

**Comment by SamTov** [comment]
It looks like the Openbabel python API required an effort in terms of installation including perhaps having to edit the CMake file directly. Doing this automatically through the install pipeline could pose some real problems so we should consider either using ase or using only the file readers of MDAnalysis.

**Comment by SamTov** [comment]
I recently found an alternative option for file reading: 

**Chemfiles**: http://chemfiles.org/chemfiles/latest/formats.html

They can read all of the files we need to read with relative flexibility. In some case, e.g. LAMMPS they do not allow for so much freedom in reading data so we would need to either augment or just keep our own readers in cases where custom data is required.

**Comment by SamTov** [comment]
We will use ase

**Comment by Luthaf** [comment]
Hi, chemfiles developer here 👋!

Just found this issue after @SamTov asked a question on chemfiles repo. You should be able to install chemfiles with pip, we provide pre-built wheels for Windows, Linux & macOS, and source build for anything else: https://pypi.org/project/chemfiles/. I'm really sorry, I just realised our documentation on installation is very outdated.

**Comment by SamTov** [comment]
Yes I did get the chemfiles working quite nicely over the weekend but as mentioned in my issue, I was worried we would not be able to collect as much custom input as we can with our reader.

Due to its speed and large applicability I would like to move ahead with chemfiles in resolution to this issue but we need to ensure that the functionality on our end does not change. I am happy to work with your project to try and make that a reality too!

**Comment by christophlohrmann** [comment]
could be closed
