### ISSUE TITLE
Reading extxyz files without lattice information

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#231]
**Describe the bug**
Only extxyz files that have certain attributes can be read by MDSuite

**To Reproduce**
Use https://github.com/nlesc-nano/auto-FOX/raw/master/tests/test_files/Cd68Se55_26COO_MD_trajec.xyz

Convert it to extxyz:

```py
from ase.io import iread, write
atoms = [x for x in iread("Cd68Se55_26COO_MD_trajec.xyz")]
write("Cd68Se55_26COO_MD_trajec.xyz.extxyz", atoms)
```

And then try to load it into MDSuite raises:

```bash
[...]
c:\users\fabia\nextcloud\data\jupyterprojects\mdsuite\mdsuite\file_io\extxyz_trajectory_reader.py in _get_species_information(self, number_of_atoms)
    245         header = self._read_header(self.f_object)  # get the header tensor_values
    246 
--> 247         box, element_index, property_groups = self._split_extxyz_properties(header)
    248 
    249         # Loop over atoms in first configuration.

c:\users\fabia\nextcloud\data\jupyterprojects\mdsuite\mdsuite\file_io\extxyz_trajectory_reader.py in _split_extxyz_properties(self, header)
    227                 Lattice parameters of the system.
    228         """
--> 229         lattice = self._read_lattice(header[1])
    230         species_index, property_summary = self._get_property_summary(header[1])
    231 

c:\users\fabia\nextcloud\data\jupyterprojects\mdsuite\mdsuite\file_io\extxyz_trajectory_reader.py in _read_lattice(self, data)
    169                     break
    170 
--> 171         if stop is not None:
    172             lattice = data[start:stop+1]
    173             lattice[0] = lattice[0].split('=')[1].replace('"', '')

UnboundLocalError: local variable 'stop' referenced before assignment
```

Might be related to #221 to allow for more file options

**Comment by SamTov** [comment]
Okay there should be some parameters in the add_data method for getting around this as I had this in mind when I wrote the original reader.

**Comment by SamTov** [comment]
As an additional note, the file that you linked is not an extxyz file, it is an xyz file which we do not support.

**Comment by SamTov** [comment]
@PythonFZ as this is not an extxyz problem and we have a .xyz file issue open in #232, can we close this issue?

**Comment by PythonFZ** [comment]
It is still an issue I think, because I converted the file to `extxyz` using ase.

The main problem is, that extxyz is not well defined and the current filereader can only read a very specific type of extxyz.
So if we are going to close this, we should put a warning in the docs, that it is an experimental feature.

**Comment by SamTov** [comment]
Sort of but an extxyz file should have an box vectors. 

The file you tried to read was an xyz not and extxyz so it's not exactly the same. We could have one reader for the both and just have it read no data in for an xyz but it might be easier to have a specific xyz reader that simply ignores all comment lines.

I guess it still is an issue, but the extxyz file reader does allow for data to be missing, just not the box vectors which I believe is in the definition of an extxyz file.

**Comment by SamTov** [comment]
@PythonFZ  I think this is resolved with the Chemfiles reader.
