### ISSUE TITLE
How to get time average MSD from numpy arrays

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#234]
**What feature would you like to see added?**
User request:

If you have the positions and timestamps as numpy arrays. What would be the best way to get the time averaged MSD of the trajectories?

**Notes**
- We should think about an easy interface to such minimalistic inputs. If there is no supported file format available we should have a description on how to convert custom files into a MDSuite reable file format.
- Related to #221

**Comment by SamTov** [comment]
I think the best thing to do is focus on writing some good tutorials on how to write your own file reader. The inner components of MDSuite are such that accessing only and MSD calculation and in particular, the time averaging component, is very difficult unless it comes through the process of batch/ensemble generator construction. 

This is also part of the documentation for the calculator class. We should have better written resources so people understand what is happening when they run some code.
