### ISSUE TITLE
MDSuite_Binary_Salt_Walkthrough does not work

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#237]
**Describe the problem**
The MDSuite_Binary_Salt_Walkthrough.ipynb` is not up to date!

The `add_experiment` function has been changed.
```py
Molten_NaCl.add_experiment(experiment_name="NaCl_1400K", 
                           timestep=0.002, 
                           temperature=1400.0, 
                           units='metal')
```
**Improvments**

Maybe remove all tutorials and keep them exclusively in the documentation, so we avoid overhead.
Maybe we can also add a test for some parts of the documentation?

I would also add that we need a clearer differentiation between the Project and the Experiment class.
For a simple analysis an experiment is often sufficient, but the mentioning of the project might cause some confusion.

**Comment by SamTov** [comment]
For now we will remove the tutorials and direct people to the documentation where it is clear how to download example data.

**Comment by SamTov** [comment]
It has been removed.
