### ISSUE TITLE
Improving RDF

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#260]
**Describe the bug**
We need to improve the species sorting of the RDF calculators.

**Some ideas**

All of the discussion here is on the `compute_species_values` method beginning line 569 if the `radial_distribution_function.py` module in the development branch

* Line 589 `particles_list = [len(self.experiment.species[item]['indices']) for item in self.experiment.species]` should be changed to only the calculator species. This would result in less loops for specific species systems.
* Line 394 `cutoff_mask = tf.cast(tf.less(tensor, cutoff), dtype=tf.bool)  # Construct the mask` The bool casting here is irrelevant. 
*  `mini_get_pair_indices` and `particle_list` should only need to be computed once but are computed in every iteration.

**Comment by PythonFZ** [comment]
Unfortunately `mini_get_pair_indices` depends on the triu indices, i.e. it depends on the iteration and is different every time

https://github.com/zincware/MDSuite/blob/97a832d569682691fec0bad75dbc43d162fe478e/mdsuite/calculators/radial_distribution_function.py#L525-L527

**Comment by PythonFZ** [comment]
My first suggestion would be, to check if the non-tf code can be converted to fast TensorFlow code or can be made faster by using a `tf.function` decorater.

This would be:
https://github.com/zincware/MDSuite/blob/97a832d569682691fec0bad75dbc43d162fe478e/mdsuite/calculators/radial_distribution_function.py#L531-L539

Maybe this can be slightly improved by a `tf.function`
https://github.com/zincware/MDSuite/blob/97a832d569682691fec0bad75dbc43d162fe478e/mdsuite/calculators/radial_distribution_function.py#L595-L597

Ideally we would also be able to parallize this loop, but that might not be possible
https://github.com/zincware/MDSuite/blob/97a832d569682691fec0bad75dbc43d162fe478e/mdsuite/calculators/radial_distribution_function.py#L591-L594

**Comment by PythonFZ** [comment]
What I've got so far is:

```py
%timeit tf.tensor_scatter_nd_update(background, indices, tf.range(tf.shape(indices)[0]))
> 14.3 s
```

```py
%%timeit
x = tf.sparse.SparseTensor(tf.cast(indices, dtype=tf.int64), tf.range(tf.shape(indices)[0]), tf.cast((atoms_per_batch, n_atoms), dtype=tf.int64))
tf.sparse.to_dense(x)
> 14 s
```

Which should already yield a good speed up. I'll continue looking into more optimization possibilities

**Comment by SamTov** [comment]
Looks good. While you're looking at the code can you also check that all references to species are to self.species and not self.experiment.species. Unless of course indices are needed but then the key should come from self.species and the indices from the experiment.

**Comment by SamTov** [comment]
Shall we close this now? I think device splitting is another issue for all calculators.
