### ISSUE TITLE
Make reading from the SQL database easier

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#272]
**What feature would you like to see added?**
It could be a nice idea to have the sql database query built inside of the calculator that generated the data. This means that all of the data used in the query is already there and users do not need to learn a new set of interface rules to make that query.

**Describe how this feature would improve the code**
It would make the code a lot more usable when it comes to exporting data

**Possible implementation**
We should have a `load=True` or something in each calculator that if it is set, the calculator tries to built a query and return the data rather than run the computation. If the data isn't there it could just run the analysis first, add it to the database and then return it.

**Comment by PythonFZ** [comment]
As proposed in #274 we can have for example

```py
experiment.load_data.RadialDistributionFunction()
```

On the back it just sets a initial variable on the `RadialDistributionFunction` calculator and an if-statement in the `__call__` method.
