### ISSUE TITLE
Inconsistent arguments

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#275]
**Describe the bug**
Some functions, like the ADF use `n_confs` as a paramter, others like the RDF use `number_of_configurations`.

We should make sure, that the arguments are unified.

**Comment by SamTov** [comment]
All of the calculators used full names until the rdf was implemented in which shortened names were used. The default is full names and this should be considered a standard.

**Comment by SamTov** [comment]
closed with #325
