### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#278]
We should consider using https://coveralls.io/ or https://coverage.readthedocs.io/en/coverage-5.5/ 
or similar to show the coverage of our tests.

This will not only motivate us to write more tests but also show progress on adding new tests as well as logging our  progress for motivation.

**Comment by SamTov** [comment]
I have been interested in adding a code coverage test for a while. I looked into some common CI stuff but it seems GitHub is pulling ahead in that respect. So I guess a sole-purpose coverage library would be better. Let's do it.
