### ISSUE TITLE
Add self.dtype to calculators

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#297]
We should make the type of the data in a calculator an attribute of the class. In this way, it is easier to track the data types when performing operation and requires only a single change. This should be done for all calculators. It will also allow us to set a standard for data types.

**Comment by PythonFZ** [comment]
Example for the dtype:
https://github.com/zincware/MDSuite/blob/3b20bd7e451966ba325ce45e873cef1334b5f159/mdsuite/calculators/calculator.py#L882-L885

**Comment by SamTov** [comment]
closed with #325
