### ISSUE TITLE
add_data does not support `pathlib.Path`

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#302]
**Describe the bug**

You can not pass a `pathlib.Path` object to the add_data method.
It does only work with strings.

Put a check `isinstance` together with `Path.as_posix()` in place, to allow working with pathlib objects

**Comment by SamTov** [comment]
Just a general question, in terms of usage, where is the benefit of using Pathlib here?

**Comment by PythonFZ** [comment]
`pathlib` is a built in library that if often used for describing file paths. Supporting it has not benefit on our side but is increasing user friendliness. 

Also I am often using it, it is OS independent and I encountered the issue that it is not supported.

**Comment by SamTov** [comment]
Yes I am aware of what it is. I was more interested in how it is seen to improve user friendliness. Of course if someone knows that they are doing with referencing files on different systems then this could be nice for them but I think for our current level of structure they would need the file anyway to make the object and so its really just additional imports.

I could also help us with checking features of a file too though which is also something to consider. The exists and what not could be helpful as a check.

In terms of future work though having a more general object be taken as input the file reader could be very interesting for remote files.

I suppose we can also look into path lib further and see what else we can get from it like the storage of absolute paths. Currently I see this difference though:

```python
import mdsuite as mds

filename = '/path/to/file'

project.add_data(filename)
```

or 

```python
import mdsuite as ids
import pathlib

filename = 'path/to/file'
file_obj = path lib.Path(filename)
project.add_data(file_obj)
```

But please correct me if I am wrong.

**Comment by PythonFZ** [comment]
Yes, this is correct, but maybe someone does not put the filename in like that.

```py
import mdsuite as ids
import pathlib

filename = 'path/to/file'
file_obj = pathlib.Path(filename)
project.add_data(file_obj)
```

Nevertheless, the fix is just adding

```py
if isinstance(file, pathlib.Path):
    file = file.as_posix()
```

and I don't see any reason in not supporting it.

**Comment by SamTov** [comment]
Is there a difference between that and what I wrote? 


Anyway, I don't an issue with supporting it I just want to see what features we can get from it. There is a reason Pathlib was invented and maybe we can get more out of that. I just want to push the discussion in that direction. As you have mentioned in the past, putting additional features in places that do not use them is something you like avoiding. In this case I think we should look at how you can get more out of Pathlib so we use its features because as it stands with this example it is just an extra line of code for particular users and a Union in the add_data method, something we also try to avoid.

**Comment by PythonFZ** [comment]
We can think about where to add it, this might need a more detailed look into some of the features.

For the Union. I think we should avoid them, especially in return values but also in general.
But in this case I do think that it makes sense because it does not affect the functionallity of the method or any of the code.
The method will immediatly convert the pathlib to a str and the functionality will be untouched.

In this case I think it makes sense. Similar to passing a list, np.array or tf.Tensor when either of them will be converted to tf.Tensor in the first lines of the method.

**Comment by SamTov** [comment]
Yes I also have no issue there. So then it is just the function argument. You take a string, convert it to a path object, then it is converted back to a string. Not unlike the generator loop over species, which, in principle, could have more function added to it but was not being used at that stage. 

So shall we open an issue somewhere considering how to use the Pathlib objects and for now just add the functionality for it?

**Comment by PythonFZ** [comment]
> Yes I also have no issue there. So then it is just the function argument. You take a string, convert it to a path object, then it is converted back to a string. Not unlike the generator loop over species, which, in principle, could have more function added to it but was not being used at that stage.

This is only one example. One could also use e.g. `Path.glob` to search for files.

> So shall we open an issue somewhere considering how to use the Pathlib objects and for now just add the functionality for it?

I don't know if it makes sense to open an issue for applying pathlib more generally in MDSuite, because if the current implementation works there is also no reason to change to a new one internally?
