### ISSUE TITLE
Add a tutorial data method.

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#332]
**What feature would you like to see added?**
We could have a data loading method for the tutorials and CI built into MDSuite which just makes a temp directory, downloads some data and changes into the temp directory for further operations.

**Describe how this feature would improve the code**
It would make loading data really easy for our test cases and also fit nicely into the api.

**Describe how this feature would work/possible implementations**
Something like this currently exists in the green_kubo example found under MDSuite/examples/scripts

**Comment by PythonFZ** [comment]
Is this resolved? We could also update the docs and give a small example for using DataHub / ZincHub.

We should sort out https://github.com/zincware/ZincHub/issues/1 first.

**Comment by SamTov** [comment]
I would not add any docs for using DataHub an Zinchub necessarily and would just write the examples using it. But yes this can be closed.
