### ISSUE TITLE
Would it be benefitial to store the HDF5 data differently

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#356]
Currently the simulation data is stored as `n_atoms, configurations, x` but usually it is batched along the `configurations` so it might be beneficial to restructure the database to store the data as `configurations, n_atoms, x` to increase I/O performance.

This would be interesting to test and discuss if it would be worth the rewriting of the code.

**Comment by christophlohrmann** [comment]
that would also coincide with the hdf5 standard.
Switching the whole database to hdf5-style would maybe make the learning curve flatter

**Comment by SamTov** [comment]
HDF5 standard or H5MD standard? Does HDF5 have standard for which axis data is expanded along? If so then we should change it without the speed test and abide by programmatic standards.

**Comment by PythonFZ** [comment]
Performance Comparison between the (n_confs, n_atoms, 3) and (n_atoms, n_confs, 3)
![image](https://user-images.githubusercontent.com/46721498/144567314-f69fd94b-1348-4428-98db-d7d0e9357c35.png)

resource to H5MD https://www.nongnu.org/h5md/h5md.html#particles-group

**Comment by PythonFZ** [comment]
Will be changed with going to H5MD
