### ISSUE TITLE
Definition of autocorrelation in TF

### ISSUE THREAD

**Issue by Fratorhe** [zincware/MDSuite#373]
**Describe the bug**
I was having problems running the test cases using the new TF functions and I built a small test case to compare the autocorrelation function. 
It seems there are differences between the definitions used in numpy or scipy with TF. 

Any idea what's going on? 

I attach here the piece of code to test it:

```python

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
from scipy.signal import correlate


def autocorr(x):
    result = np.correlate(x, x, mode='full')
    return result[int(result.size / 2):]


x = np.linspace(0, 20, 501)
y = np.sin(x)

autocorr_numpy = autocorr(y)
autocorr_scipy = correlate(y, y, mode='full', method='auto')[int(len(y) - 1):]

autocorr_tf = tfp.stats.auto_correlation(y, axis=0, normalize=False, center=False)

plt.plot(autocorr_numpy, label='numpy')
plt.plot(autocorr_scipy, label='scipy')
plt.plot(autocorr_tf, label='tf')

plt.legend(loc='best')
plt.show()

```

**Comment by SamTov** [comment]
The top autocorrelation does no use zero padding. The outcomes are identical up to the point where the zero-padding comes in. This is why we also now have an integration range argument which allows one to choose where the integral is taken.

**Comment by SamTov** [comment]
The discussion over whether one can use zero-padding or not is much more debated. In principle, if you know that you are in a region of noise, it should be fine. This is however quite difficult to prove and so we should perhaps not take that upon ourselves.

**Comment by Fratorhe** [comment]
mm could be that...
Indeed, I tried with this: https://stackoverflow.com/questions/66062998/autocorrelation-with-tensorflow 
And it gives the same results of numpy and scipy. 

What do you suggest to do?
Re-implement using that stackoverflow answer? 
Or may be a way to do it with tfp.stats.auto_correlation?

**Comment by SamTov** [comment]
We should not include zero padding. We can't be sure that we aren't manipulating relevant data so I don't want to release a calculator that makes such a large assumption. Using the integration range I have successfully extracted the diffusion coefficients I get from the zero-padded version. What I want to do is make an integration computation over all possible data range values and have a slider that can display them to make that easier.

**Comment by Fratorhe** [comment]
I am a little bit lost in the math I think...
Any reference in mind I can read?

**Comment by SamTov** [comment]
http://www.it.uom.gr/teaching/linearalgebra/NumericalRecipiesInC/c13-2.pdf

This one isn't bad

**Comment by Fratorhe** [comment]
> The top autocorrelation does no use zero padding. The outcomes are identical up to the point where the zero-padding comes in. This is why we also now have an integration range argument which allows one to choose where the integral is taken.

But the outcomes from the two implementations (numpy vs tfp) are different in orders of magnitude. There is something else that I am not understanding here.

**Comment by SamTov** [comment]
Did you copy the code from the imlpementations in MDSuite? Because that does make a difference yes. I will go back and take a look today to make sure it is working correctly.

**Comment by SamTov** [comment]
```python
vacf = self.args.data_range * tfp.stats.auto_correlation(
            ensemble, normalize=False, axis=1, center=False
        )
```

**Comment by SamTov** [comment]
There is this multiplication by the data_range which is done in the pre-factor. TF seems to do it automatically. If you include this then they match but the numpy/scipy decay faster which would be due to padding.

![image](https://user-images.githubusercontent.com/47057691/140502539-f378eecf-f97d-4f44-a4a9-bb17c9937ae0.png)


This did come up when I first implemented it as I worked with the tfp package to make sure it matched our GK. I will go back and compare it for diffusion to see if I missed something.

**Comment by Fratorhe** [comment]
Yes, that's what I was seeing indeed. 
I guess if you use an appropriate integration time, it should be ok. 
The problem I'd say is to define that value.

**Comment by SamTov** [comment]
Yes but this is always a problem. In this case for example, the long time values are not redundant but are be treated as such. This is problematic. If you apply it to real simulation data you will see it converge to around 0 and then fluctuate. You can handle the fluctuations with averaging over values and in this way, we need not make assumptions about convergence.

**Comment by Fratorhe** [comment]
I had a look to statsmodels (https://www.statsmodels.org/dev/generated/statsmodels.tsa.stattools.acf.html) and in their code they use `min(10 * np.log10(nobs), nobs - 1)` as the number of lags. 
I do not really know where they got this number, I went through the references they have in the reference page, but I did not find an explanation. 
However, this number did not provide good results for thermal conductivity. Instead, using `min(50 * np.log10(nobs), nobs - 1)` provided a good result. 

This could be a good default value for the integration time?

**Comment by SamTov** [comment]
So currently there is not good method for doing this, in the new plotting I have done up we plot the running integral over the acf so you can see when it converges. However, to come back to the initial problem. With the tfp implementation there is an additional mulitplication of the data range right where the acf is computed:

```python
vacf = self.args.data_range * tfp.stats.auto_correlation(
            ensemble, normalize=False, axis=1, center=False
        )
```
which brings it to the original scipy magnitude at t=0 as required. We do then divide by this number and so it is of course possible for us to remove this unnecesary computation. I have checked this w.r.t the scipy calculations and the plots match. I leave below an unfinished example of the new plot structure and will close the issue as the initial problem has been resolved.

![image](https://user-images.githubusercontent.com/47057691/143311101-5db7a8f2-52d2-4198-9e69-9bdda294eed5.png)
 

**Fun Additional Fact**

I ran a speed comparison while checking that scipy == tfp and found scipy: 27s, tfp: 1s
