### ISSUE TITLE
LaTeX rendering does not work properly (in Jupyter?)

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#374]
**Describe the bug**
When using Jupyter Lab the LaTeX formulas displayed by Bokeh do not render.
This might have something todo with MathJax or Jupyter but it needs to be resolved.

**To Reproduce**
Run any calculator in Jupyter Lab that has LaTeX axis labels.

Using Bokeh `2.4.1`

**Screenshots**
![image](https://user-images.githubusercontent.com/46721498/140524205-560cf867-90fb-47e0-aa4f-a6962c613937.png)

**Comment by Fratorhe** [comment]
Latex does not seem to be natively supported: 
https://docs.bokeh.org/en/latest/docs/user_guide/extensions_gallery/latex.html 

I do not think it is necessary to have Latex in these figures. 
IMO Latex is best for figures that will go in a paper, and usually users will prepare them elsewhere and spend quite some time to get them nice.

I would keep Bokeh for exploratory graphs.

**Comment by PythonFZ** [comment]
It is https://docs.bokeh.org/en/latest/docs/user_guide/styling.html#latex and we need axis labels.
I don't think that the current labels are suitable for displaying the results.

**Comment by Fratorhe** [comment]
Actually the problem is with the version of Bokeh. 
It only became supported in the lastest (2.4.1). 
When I installed MDSuite I got Bokeh 2.3.3, I guess because of compatibility? 

In any case, with Bokeh 2.4.1 you don't need to do anything.

**Comment by PythonFZ** [comment]
I am using Bokeh 2.4.1

**Comment by Fratorhe** [comment]
Then maybe the problem is with Jupyter only? in the normal html I see it properly.

**Comment by SamTov** [comment]
So when we first had this issue it was a Bokeh version. But due to some other conflict we had to change it. Just check that the labels are written the same way. Are you plotting the same thing? There was a specific way to have the labels written for it to work and it seems during a merge some were left behind.

Latex would be nice in the figure but as you mentioned and I believe we should stay with, MDSuite is NOT for making publication quality plots. It is for data exploration and analysis. I do think we need to work to get LaTeX working in the plots.

**Comment by SamTov** [comment]
I am not sure if Bokeh 2.4.2 fixes this, could you check?

**Comment by PythonFZ** [comment]
I checked with GK diffusion and it still does not render properly.

**Comment by SamTov** [comment]
So it's really something going on with the Jupyter interface then. I am not sure if the syntax should be different for Jupyter. I will set up tests locally and try to work it out.

**Comment by PythonFZ** [comment]
It could be possible that jupyter lab has some restrictions in JS being executed. And bokeh does not render the formulas but passes them to I think MathJax.

**Comment by SamTov** [comment]
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/47057691/144221813-f6d89a59-a6f6-4464-8647-157da9b1f71f.png">

With the updated Jupyter it is fine.

**Comment by SamTov** [comment]
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/47057691/144222372-f21a0d0a-8fd2-42be-84c2-1178130660c5.png">

Also fine in Jupyter-lab
