### ISSUE TITLE
publish package on PyPi

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#377]
Now, that most of the code is tested we should be able to soon publish MDSuite on PyPi.

# Summary
Add all issues that are holding us back to the PyPi milestone

**Comment by SamTov** [comment]
These are the ones I would like closed before just to avoid immediate updates in version number.

#375 
#373 
#369 
#356 
#351
#327 
#233 
#221 
#215 
#40

**Comment by PythonFZ** [comment]
Perfect, I added them to the milestone.

**Comment by SamTov** [comment]
If you have any additional ones feel free to add them in.

**Comment by PythonFZ** [comment]
I think this can be closed
