### ISSUE TITLE
experiment.species should be a dataclass

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#392]
Currently `experiment.species` is a dictionary but it would be benefitial to make it a dataclass, so instead of `species['Na']['charge']` one can do `species['Na'].charge`. This would also set the available keys and make things easier for implementing.

**Comment by christophlohrmann** [comment]
the dataclass could be very similar (or actually be) mdsuite.database.simulation_database.SpeciesInfo (from PR #372).
I do not know how to store that in the SQL, though

**Comment by PythonFZ** [comment]
It would not be to difficult. We can adapt
https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/experiment_database.py#L196-L242
to work with the dataclass.
We would have to convert it to a JSON serializeable dict and then we can pass it through
https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/scheme.py#L184
