### ISSUE TITLE
remove the `project/<project>/databases` directory

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#393]
The HDF5 database can in principle be dumped directly into `Project/<project>/<experiment_name>.hdf5` or the directory should be renamed to `database` because it won't contain more than one.

**Comment by SamTov** [comment]
I didn't realise there was a project/databases directory? 

Under the Project class there should be a directory for each experiment is there not? Within which there is a database/database.hdf5 file which I agree could be put into the main directory of the experiment. Or is there no longer a subdirectory for experiments?

**Comment by PythonFZ** [comment]
> I didn't realise there was a project/databases directory?
> 
> Under the Project class there should be a directory for each experiment is there not? Within which there is a database/database.hdf5 file which I agree could be put into the main directory of the experiment. Or is there no longer a subdirectory for experiments?

I fixed that in the description. I forgot to put in the experiment directory
