### ISSUE TITLE
`perform_transformation` should work similar to `run`

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#395]
We have `project.experiments.experiment.perform_transformation("TranslationalDipoleMoment")` but it would be nicer to have `project.experiments.experiment.perform_transformation.TranslationalDipoleMoment()`

**Comment by SamTov** [comment]
I'd actually prefer to put it under run if it is possible.

**Comment by PythonFZ** [comment]
So have `exp.run.TanslationalDipoleMoment` - this would make it harder to distinguish between transformations and calculators though, but it shouldn't be an issue I guess.

**Comment by SamTov** [comment]
I would have `project.run.TransformationName()`

They are indistinguishable from the calculators if you really want to call them. It is unlikely that people will call them often and it is as likely that someone randomly types in the wrong calculator as it is that they accidentally call a transformation instead.

**Comment by PythonFZ** [comment]
> I would have `project.run.Transformation()`

How would you define which transformation to run?

`project.run.Transformation("TranslationalDipoleMoment")` without autocompletion or `exp.run.<transformation>()`?

**Comment by SamTov** [comment]
I would have it as autocompletion. Just used Transformation as  dummy, **updated it**

**Comment by christophlohrmann** [comment]
I like the common syntax. The user does not have to know that there is a difference between a transformation and a calculation

**Comment by SamTov** [comment]
I 100% agree.
