### ISSUE TITLE
Use `tf.data.Dataset` and prefetching in the file readers

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#397]
We can make the most out of reading and writing in parallel when we prefetch the data and simultaneously write it to the HDF5 Database.
One approach that we already use a lot in MDSuite would be tf.data.Datasets with generators and prefetching.

**Comment by SamTov** [comment]
Parallel writing to HDF5 is not so trivial from memory but we can read, process, and stage in parallel

**Comment by PythonFZ** [comment]
This is what I meant. You can read the next batch in from the trajectory file while writing to the database. 
Parallelize the read-write process not the write itself.

**Comment by SamTov** [comment]
In the end, I don't think this is possible with tensor flow and I believe in the future we will leave TF behind altogether in favour of Jax or our own multiprocessing implementation so I will close this for now. We should come back to parallel reading at some point but I think a custom MP class will do the trick.
