### ISSUE TITLE
what was the resoning behind simulation_database.get_database_summary(self):

### ISSUE THREAD

**Issue by christophlohrmann** [zincware/MDSuite#399]
This function should list the properties that are stored for each species by reading the keys of the database.
why does it need ``var_names`` to check against?

https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/simulation_database.py#L670-L682

**Comment by SamTov** [comment]
This was a summary method to show what is in the database. The idea behind it was that one may finish a project and leave it around for a long time. When they come back to it they want to know what is in it. I believe it had the var names there to check for system properties before looking into the atom-wise properties but it is quite old at this point so the structure of the database may render this now redundant. There was an accompanying experiment method to print a summary of the experiment but this is also now not used as we work through the project class.

**Comment by christophlohrmann** [comment]
since #447 , this method returns the full summary of all keys in the database
