### ISSUE TITLE
simulation_database should use a context manager

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#400]
The `simulation_database.py` often uses open and close statements.
We should try to avoid this because as far as I know HDF5 DBs are likely to corrupt when not closed properly.

We should replace every `hf.File()` with a context manager for safety.

**Comment by SamTov** [comment]
What files have you seen this in? It would be much more helpful to list at least the one that made you write the issue as we have been trying to weed this out for a while.

**Comment by PythonFZ** [comment]
I mentioned the file being `simulation_database.py`. You can go through the file and search for `hf.File` or `open`.
For an example see #399 
but also
https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/simulation_database.py#L109
https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/simulation_database.py#L198
https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/simulation_database.py#L609
https://github.com/zincware/MDSuite/blob/bc41b70194a8dc4c8af288ca120363e15d0580b9/mdsuite/database/simulation_database.py#L614

please check the file!

**Comment by SamTov** [comment]
Sorry I thought I read the simulation database and not the name of the file as I know that it is also possible that these still exist in other parts of the code. Thank you for the examples.
