### ISSUE TITLE
Save bokeh html file

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#401]
**Describe the bug**
Currently a bokeh plot is saved as `<calculator>.html` in the root directory.
It might be benefitial to save the html files in `project/experiment/figures` because that directory is currently not used but created.
It would also avoid overwritting plots when using `project.run`

**Comment by MarcBrueck** [comment]
Done, gonna do a PR on main later

**Comment by PythonFZ** [comment]
No - it is not resolved, because the PR isn't merged yet!
