### ISSUE TITLE
We could implement TensorFlow in the distinct diffusion coefficients calculation.

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#409]
**What feature would you like to see added?**
In the Green-Kubo self diffusion coefficients we use TensorFlow-probability (tfp) to perform autocorrelation:

```python
vacf = self.args.data_range * tfp.stats.auto_correlation(
            ensemble, normalize=False, axis=1, center=False
        )
        vacf = tf.reduce_sum(tf.reduce_sum(vacf, axis=0), -1)
```

In the case of distinct diffusion we need a cross-correlation function, not an auto-correlation which tfp does not have. Instead we use the standard scripy approach with a lot of loops:

```python
        for i in range(len(data[dict_ref[0]])):
            for j in range(i + 1, len(data[dict_ref[1]])):
                if i == j:
                    continue
                else:
                    vacf += sum(
                        [
                            signal.correlate(
                                data[dict_ref[0]][i][:, idx],
                                data[dict_ref[1]][j][:, idx],
                                mode="full",
                                method="auto",
                            )
                            for idx in range(3)
                        ]
                    )
```

The `tf.nn.convolution` operation computes cross correlation as its implementation of convolution and can therefore in principle be applied to this problem. It looks like it must be mapped as an operation in order to achieve the parallelisation we might want but would be a significant speed-up over the current approach.

**Comment by PythonFZ** [comment]
We should probably test the performance increase before we implement this. 
I can try to write a simple notebook to check that.

**Comment by SamTov** [comment]
Jax has a direct implementation https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.signal.correlate.html?highlight=correlate#jax.scipy.signal.correlate
