### ISSUE TITLE
Documentation: Coordinate Unwrapper code does not work

### ISSUE THREAD

**Issue by tobiasmerkt** [zincware/MDSuite#424]
**Describe the bug**
Link: https://github.com/zincware/MDSuite/blob/293a96e549dbd142c879c18034b1db40b8932171/docs/source/tools.rst
The code in the documentation produces an error.

```python
import mdsuite as mds
NaCl = mds.Experiment(...)
```
 **Error Message**
   line 2, in <module>
    NaCl = mds.Experiment(...)
TypeError: __init__() missing 1 required positional argument: 'experiment_name'

**Comment by SamTov** [comment]
Please remove the section on unwrapping coordinates and writing xyz files from this section. Neither are supported like this anymore.

**Comment by PythonFZ** [comment]
Is this resolved with #416 ?
