### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by tobiasmerkt** [zincware/MDSuite#427]
- [ ] **1. Pages empty**
Even though the following pages exist, they do not include any text.

- [ ] [Phonon spectrum](https://github.com/zincware/MDSuite/blob/293a96e549dbd142c879c18034b1db40b8932171/docs/source/_theory/phonon_spectrum.rst)
- [ ] [Isothermal compressibility](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/isothermal_compressibility.rst)
- [ ] [Tensor Operations in MD Suite](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/tensor_operations_in_mdsuite.rst)
- [ ] [Autocorrelation in MD Suite](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/autocorrelation_in_mdsuite.rst)
- [ ] [Ensemble average](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/ensemble_average.rst)
- [ ] [Fluctuation dissipation theorem](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/fluctuation_dissipation_theorem.rst)
- [ ] [Green Kubo relations](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/green_kubo_relations.rst)
- [ ] [Einstein relations](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/einstein_calculations.rst)
- [ ] [Onsager coefficients and dynamics](https://github.com/zincware/MDSuite/blob/main/docs/source/_theory/onsager_coefficients_and_dynamics_in_md_simulations.rst)

- [ ] **2. Jumping to next file does not work**
When clicking on "Next" in the [Onsager Coefficients and Dynamics in MD simulations ](docs/source/_theory/onsager_coefficients_and_dynamics_in_md_simulations.rst), the documentation does not open the next file "Diffusion Coefficients" but instead opens the user guide.

**Comment by SamTov** [comment]
Is it present in the visual documentation? If so, please make sure it does not show up in any table of contents as it is not implemented.
