### ISSUE TITLE
Check missing indicies

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#432]
We introduced 
https://github.com/zincware/MDSuite/blob/1ca1f88e83c2c007706aba20c12f1be1221f2442/mdsuite/database/experiment_database.py#L237-L239
to remove the indices and only use the length.

There might be some parts of the code, e.g. sorting or map_molecules that still remain on it.

These functions need tests and should be checked before continuing with #392

**Comment by SamTov** [comment]
I think this is now resolved? @PythonFZ

**Comment by PythonFZ** [comment]
I'm not sure - I think the `indices` key is still passed through when setting the species dict. But we can certainly consider it mostly fixed. What about #433 ?
