### ISSUE TITLE
`ase.Atoms`-like object for HDF5

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#458]
This is just an idea I had without considering all the strings attached to it and how complicated it could be to implement or how much it would differ from the current implementation.

For the calculators we e.g. currently have:

```py
self.loaded_property = simulation_properties.velocities
batch_ds = self.get_batch_dataset(species_values)
ensemble_ds = self.get_ensemble_dataset(batch, species_values)
```
with 
https://github.com/zincware/MDSuite/blob/f1c4475c3cd3e3a6758b3c252d3138d9bad6a25e/mdsuite/calculators/trajectory_calculator.py#L325-L345
https://github.com/zincware/MDSuite/blob/f1c4475c3cd3e3a6758b3c252d3138d9bad6a25e/mdsuite/calculators/trajectory_calculator.py#L364-L388

I think, we could have something like the following:

```py
for batch in configuration:  # or if we need **kwargs configuration.batch(**kwargs)
    for ensemble in batch:   # or if we need **kwargs batch.ensemble(**kwargs)
        compute(ensemble.velocities)
```
for all https://github.com/zincware/MDSuite/blob/f1c4475c3cd3e3a6758b3c252d3138d9bad6a25e/mdsuite/database/simulation_data_class.py#L33

This would be easier to test, because it is in principle completly isolated from the rest of MDSuite and could also be returned to the user if they want to work with the data and benefit from the memory management.

**Comment by christophlohrmann** [comment]
not sure I understand the point. which part of the code (which modules' responsibility) are we talking about?

**Comment by PythonFZ** [comment]
I think this would affect everything that loads data from the HDF5 database, transformations and calculators. 
For example

https://github.com/zincware/MDSuite/blob/44f298f65ce2c894752eec27f0d055883d133b0c/mdsuite/transformations/unwrap_coordinates.py#L203-L228

could be reduced to something like this (there might be some challanges here though)

```py
for index, x in tqdm(
    enumerate(data_set.batch(species=species)),
    ncols=70,
    desc=f"{species} unwrapping",
    total=self.n_batches + loop_correction,
):
    if index == 0:
        data, state, last_conf = self._transformation(
            np.array(x.Positions), state
        )
```

**Comment by PythonFZ** [comment]
Further comments on the API can be posted over here https://github.com/zincware/ZnH5MD
For now I would close this issue and we can open a new one where we discuss implementation details on how to put ZnH5MD into MDSuite.
