### ISSUE TITLE
position property naming

### ISSUE THREAD

**Issue by christophlohrmann** [zincware/MDSuite#459]
currenty we have 
```
Positions
Scaled_Positions
Unwrapped_Positions
Scaled_Unwrapped_Positions
```

I think there is quite the potential for confusion when calculators and transformations work with positions, thinking they are already scaled (I am pretty sure all occurences of Unwrapped_Positions actually would like the Scaled_Unwrapped_Positions). I would therefore propose a renaming to:

```
Normalized_Positions
Positions
Normalized_Unwrapped_Positions
Unwrapped_Positions
```

We could even go as far as making Unwrapped the standard and write Wrapped_** for the others.

**Comment by christophlohrmann** [comment]
note: with #447 this can be done in 10mins

**Comment by SamTov** [comment]
It would also fall in line with Chemfiles to by default unwrap positions where possible upon reading.

**Comment by christophlohrmann** [comment]
I do not think that instant unwrapping is needed.
Any transformation that requires unwrapped coordinates will trigger the unwrapping automatically.
If calculators do the same, then unwrapping falls in line with all the other 'just in time' transformations

**Comment by christophlohrmann** [comment]
turns out I am stupid. I got the scaled-unscaled wrong. ``pos`` is in [0, box_l] and ``pos_scaled`` is in [0,1]. My confusion then only came from the ``scale_coordinates`` transformation that actually "unscales" the coordinates.
