### ISSUE TITLE
Decide how to manager particle groups such as molecules

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#477]
**What feature would you like to see added?**
Currently molecules are their own seperate dict. We could subclass them from the species data class and make a new data class or consider another option. The only constraint is that molecules and species must remain identifiably separated. This is essential to function of MDSuite. If one cannot differentiate between a species and a molecular species, i.e a group of atoms or particles, then other calculators will be wrong.

**Comment by PythonFZ** [comment]
I will add the already made points by @christophlohrmann

> Not fully thought out, but could a molecule derive from species? We could do that if all species attributes also exist for molecules (which I think they do??). Molecules would then only add their specific information. The transformations/calculators by default loop over all species, we could make it like run_transformation(subject_names:list[str]=None, all_species = True, all_molecules = False so the user can switch between species, molecules or their own list of species/molecules

> no objection on the general thought here from me. But I prefer it a child of species and not to add a default-inactive argument to species. In that way the normal species stays "unpolluted" by stuff it does not need for itself

**Comment by SamTov** [comment]
@PythonFZ is this now resolved with #497
