### ISSUE TITLE
Passing arguments post-operation calculators

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#481]
We should decide on how to pass arguments to calculators which rely on the computation of another calculator. At the moment this is typically only RDFs but we also have Nernst-Einstein computations which could use such a feature. 

Currently, there is no parameter information passed, the calculator just tries to load an arbitrary RDF from the SQL database and runs one if none exists. This means that if you computed 3 RDFs under different conditions and want to look at the coordination numbers of all of them, you cannot. This becomes quite important if you study molecules as you may want to look at the atomistic coordination numbers or KB integrals as well as those of the molecules which is not possible.

My suggestion is as follows:

```python
rdf_data = experiment.run.RadialDistributionFunction()

cn_data = experiment.run.CoordinationNumbers(rdf_data, savgol_filter_parameters, ...)
```
Or for Nernst Einstein 
```python
self_diffusion_data = experiment.run.EinsteinDiffusion()
correlated_diffusion_data = experiment.run.GreenKuboDistinctDiffusion()

ne_cond = experiment.run.NersnstEinstein(
        self_diffusion = self_diffusion_data, correlated_diffusion = correlated_diffusion_data
)
```

In cases where defaults can be had, i.e those relying on RDFs, we can set the default in the calculator to call an RDF computation with the default parameters and proceed. 

Any and all comments and thoughts are welcomed.
@Fratorhe @PythonFZ @christophlohrmann @MarcBrueck

**Comment by PythonFZ** [comment]
I like it!

**Comment by Fratorhe** [comment]
I think that's what makes the most sense to do. 
Like this you can also retrieve the appropriate one from the SQL database and pass it. 
Very clean.

**Comment by MarcBrueck** [comment]
Sure, it should just be clear how the rdfs are named and how to access them,  because that was not clear to me.

**Comment by christophlohrmann** [comment]
I like this idea of stringing calculators together. It also makes it nice and explicit for the user which calculations are performed.
In the documentation we just need to state which calculator to call for obtaining the data that is needed.

Side note:
The fact that ``EinsteinDiffusion`` returns ``self_diffusion_data`` and ``GreenKuboDistinctDiffusion`` returns ``correlated_diffusion_data`` gives food for thought about the naming of these calculators.
Could the calculation of MSDs be separated from the calculation of the diffusion coefficients?

**Comment by SamTov** [comment]
@christophlohrmann  It certainly could be. I have some further ideas for the future API of MDSuite regarding how calculations are called as the project starts to grow. In the coming months/year we may see a lot of additions from varying fields and so we may need a better approach for narrowing down which functions come from where. I suggest we have some sort of general assembly and form a type of council to make these decision and other large decisions for MDSuite.
