### ISSUE TITLE
Check log Level for log file

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#482]
I just realized that the logger does neither print log.debug() lines nor store them in the mdsuite.log file. 
where can you even see log.debug() lines then?

_Originally posted by @MarcBrueck in https://github.com/zincware/MDSuite/pull/478#discussion_r794290759_

**Comment by SamTov** [comment]
Does it depend if the logger is set to DEBUG?

**Comment by PythonFZ** [comment]
There should be two loggers, one for the file which should log everything (DEBUG) and one standard out logger which should be INFO.
