### ISSUE TITLE
how to adjust mdsuite logging?

### ISSUE THREAD

**Issue by christophlohrmann** [zincware/MDSuite#494]
I knew we talked about this before, but what was the reason that I get swamped with debug messages in a lengthy format?
Is there a way to control mdsuite's loglevel?

**Comment by PythonFZ** [comment]
The MDSuite log level can be adjusted here
https://github.com/zincware/MDSuite/blob/6ed32d47a62b3719c96f0dc6cbc7fb61d21f9099/mdsuite/__init__.py#L52
for the `sys.stdout` logger and here
https://github.com/zincware/MDSuite/blob/6ed32d47a62b3719c96f0dc6cbc7fb61d21f9099/mdsuite/project/project.py#L139
for the file logger.

**Comment by SamTov** [comment]
The default should always be INFO though right?

**Comment by PythonFZ** [comment]
> The default should always be INFO though right?

For `sys.stdout` it would be INFO but the file logger is `DEBUG` so you can check if something went wrong.

**Comment by christophlohrmann** [comment]
I agree, as long as it really only writes to file

**Comment by PythonFZ** [comment]
@christophlohrmann is this resolved?
