### ISSUE TITLE
Issue with reading `extxyz` files produced by ASE

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#498]
**Describe the bug**
Can not add extxyz data to MDSuite

# Error message
```
~\AppData\Local\Temp/ipykernel_5328/2793412633.py in <module>
----> 1 project.add_experiment(
      2     name="LiCl2",
      3     timestep=0.001,
      4     temperature=900,
      5     units="metal",

c:\users\fabia\pycharmprojects\mdsuite\mdsuite\project\project.py in add_experiment(self, name, timestep, temperature, units, cluster_mode, active, simulation_data)
    232 
    233         if simulation_data is not None:
--> 234             self.experiments[name].add_data(simulation_data)
    235 
    236         return self.experiments[name]

c:\users\fabia\pycharmprojects\mdsuite\mdsuite\experiment\experiment.py in add_data(self, simulation_data, force, update_with_pubchempy)
    499         else:
    500             proc = _get_processor(simulation_data)
--> 501             self._add_data_from_file_processor(
    502                 proc, force=force, update_with_pubchempy=update_with_pubchempy
    503             )

c:\users\fabia\pycharmprojects\mdsuite\mdsuite\experiment\experiment.py in _add_data_from_file_processor(self, file_processor, force, update_with_pubchempy)
    535         database = Database(self.database_path / "database.hdf5")
    536 
--> 537         metadata = file_processor.metadata
    538         architecture = _species_list_to_architecture_dict(
    539             metadata.species_list, metadata.n_configurations

c:\users\fabia\pycharmprojects\mdsuite\mdsuite\file_io\file_read.py in metadata(self)
     62     def metadata(self):
     63         if self._metadata is None:
---> 64             self._metadata = self._get_metadata()
     65         return self._metadata
     66 

c:\users\fabia\pycharmprojects\mdsuite\mdsuite\file_io\extxyz_files.py in _get_metadata(self)
    134             )
    135             header_1 = file.readline()
--> 136             sample_rate = int(round(_get_time(header_1) - _get_time(header)))
    137 
    138         species_list = get_species_list_from_tabular_text_reader_data(

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

# Reproduce

```
project = mds.Project()
project.add_experiment(
    name="LiCl",
    timestep=0.001,
    temperature=900,
    units="metal",
    simulation_data="traj.extxyz"
)
```
with the following as content of `traj.extxyz`
[traj.txt](https://github.com/zincware/MDSuite/files/8067230/traj.txt)

### Header lines

- works: `Lattice="13.3 0.0 0.0 0.0 13.3 0.0 0.0 0.0 13.3" Properties=species:S:1:pos:R:3:forces:R:3 cutoff=-1.0 energy=-30664.29709663569 nneightol=0.0 i=0, pbc="T T T" time=0.000,`
- does not work: `Lattice="13.3 0.0 0.0 0.0 13.3 0.0 0.0 0.0 13.3" Properties=species:S:1:pos:R:3:momenta:R:3:forces:R:3 energy=-317.7220481319967 pbc="T T T"`

**Comment by SamTov** [comment]
Can you please print the header line of the file you tried to read?

**Comment by SamTov** [comment]
I would suggest this comes down more to how (assumedly ase)  defines extxyz. Because ase says all xyz is extxyz, they do not have strict standards for the dumping of the files. In this case, we could add a try statement and consider these to be extxyz files, or we raise an error saying that this is not a true extxyz file.

**Comment by PythonFZ** [comment]
I do think we should try to support ASE, it is a often used tool and we will use it ourselves for running MD.
Do you know how we produced the `extxyz` files we have that work?

**Comment by SamTov** [comment]
It isn't about supporting ase as much as passing this file over to an xyz file reader rather than the extxyz. Or we allow the extxyz to be completely general. As extxyz is not a well-defined format we can take either approach.
