### ISSUE TITLE
Compute Volume dynamically and don't store it

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#499]
Currently the experiment volume is computed in 
https://github.com/zincware/MDSuite/blob/68a475975e4c5d8b0ee9e0432ea06d2b55b3a1fc/mdsuite/experiment/experiment.py#L621
so if you have some `xyz` data and then add the cell via `experiment.cell = [13.3, 13.3, 13.3]` the volume is not updated.

I would suggest computing the volume on the fly via `volume = np.prod(cell)` and not storing it.
This would be even more imporant for simulations with changing box size.

**Comment by SamTov** [comment]
Perhaps it can be something like the charge on species currently wherein it can be fixed or changing. Broadcasting would make this easy to apply. In any case, removing the volume attribute in favour of only having box vectors and doing the computation over either the experiment stored box vectors of hdf5 stored vectors in the case of changing box size.
