### ISSUE TITLE
Add `mds.units.METAL`

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#533]
We could add the following enums for user / developer friendlier code:

```py
md_project.add_experiment(
    name="KCl", timestep=0.002, units='metal', temperature=1200.0, simulation_data=KCl_data
)
# vs
md_project.add_experiment(
    name="KCl", timestep=0.002, units=mds.units.METAL, temperature=1200.0, simulation_data=KCl_data
)
```

They already exist but can not be used from outside
https://github.com/zincware/MDSuite/blob/ffb8ae91b1fef8495a2e1b69e80ba4ad82979272/mdsuite/utils/units.py#L95

**Comment by SamTov** [comment]
Yeah I really like it.
