### ISSUE TITLE
prohibit experiment names starting with a number

### ISSUE THREAD

**Issue by PythonFZ** [zincware/MDSuite#537]
**Describe the bug**

If you use something like

```py
project.add_experiment(
        name="273K_ML",
        timestep=0.01,
        temperature=273.0,
        units="metal",
        simulation_data=file_reader
    )
```

you can not access it via

```py
project.experiments.273K_ML
```

There are two possible solutions:
- rename experiments automatically
- prohibit names starting with a number

I'm in favor of raising an error when someone tries to use an experiment name starting with a number.

**Comment by SamTov** [comment]
Yeah if it can end in a number no reason to make it possible to start with one, I agree to just raising an error.
