### ISSUE TITLE
System wide observables and data loading

### ISSUE THREAD

**Issue by SamTov** [zincware/MDSuite#568]
**Describe the bug**
There is a mismatch in naming convention for system wide observables depending on whether they have been loaded from a file or produced using a transformation.

In the case that it is loaded from a file they are placed under the `Observables` group. However, if one produces something system-wide like an ionic current it will be placed directly, into an `Ionic_Current` group. This means that if someone wants to use an observable that was read in from a file for a calculation, it will fail as it does not know from where it should load the data.

**Expected behaviour**
The convention should be clear and in the move to H5MD structure, should likely be the `Observables` group convention. However, none of the calculators use this convention...

**Comment by christophlohrmann** [comment]
which one do we want? ``Observables`` as a "parent folder" for the groups or just their name?

**Comment by SamTov** [comment]
I think Observables is better
