### ISSUE TITLE
Error in Molten_Salt_comparison : 'Dataset' object has no attribute 'nbytes'

### ISSUE THREAD

**Issue by okunoyukihiro2** [zincware/MDSuite#602]
Dear MDSuite Developers 

I'm trying to use MDSuite and run example code "Molten_Salt_comparison.ipynb" in examples directory.

However, error has occur in 

NaCl_experiment = md_project.add_experiment(
    name="NaCl", timestep=0.002, units='metal', temperature=1200.0, simulation_data=NaCl_data
)

with error message 
AttributeError: 'Dataset' object has no attribute 'nbytes'

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_2230045/1711953086.py in <module>
----> 1 NaCl_experiment = md_project.add_experiment(
      2     name="NaCl", timestep=0.002, units='metal', temperature=1200.0, simulation_data=NaCl_data
      3 )
      4 KCl_experiment = md_project.add_experiment(
      5     name="KCl", timestep=0.002, units='metal', temperature=1200.0, simulation_data=KCl_data

~/anaconda3/lib/python3.8/site-packages/mdsuite/project/project.py in add_experiment(self, name, timestep, temperature, units, cluster_mode, active, simulation_data, update_with_pubchempy)
    239 
    240         if simulation_data is not None:
--> 241             self.experiments[name].add_data(
    242                 simulation_data, update_with_pubchempy=update_with_pubchempy
    243             )

~/anaconda3/lib/python3.8/site-packages/mdsuite/experiment/experiment.py in add_data(self, simulation_data, force, update_with_pubchempy)
    496         else:
    497             proc = _get_processor(simulation_data)
--> 498             self._add_data_from_file_processor(
    499                 proc, force=force, update_with_pubchempy=update_with_pubchempy
    500             )

~/anaconda3/lib/python3.8/site-packages/mdsuite/experiment/experiment.py in _add_data_from_file_processor(self, file_processor, force, update_with_pubchempy)
    547         self.version += 1
    548 
--> 549         self.memory_requirements = database.get_memory_information()
    550 
    551         # set at the end, because if something fails, the file was not properly read.

~/anaconda3/lib/python3.8/site-packages/mdsuite/database/simulation_database.py in get_memory_information(self)
    540             for item in database:
    541                 for ds in database[item]:
--> 542                     memory_database[join_path(item, ds)] = database[item][ds].nbytes
    543 
    544         return memory_database

AttributeError: 'Dataset' object has no attribute 'nbytes'

Is it version error of MDSuite?

**Comment by SamTov** [comment]
Hi @okunoyukihiro2, thanks for using our package. This looks like a problem with the h5py library version. The `bytes` attribute only appears, I believe, after version 3.0 of h5py.  Perhaps a conflicting version has been installed. Try to run:

```sh
pip install --upgrade h5py
```
and rerun the notebook. Remember to remove the old MDSuite project; otherwise, the old database will still exist, and the attribute won't be in the dataset. Let me know how you go!

**Comment by okunoyukihiro2** [comment]
Thank you for response.  
According to your advice,  I could run the examples code. 

Sincerely,

Yukihiro Okuno.
